### PR TITLE
Add redshift support

### PR DESCRIPTION
**Pull request by TreyLawrence**

### CODE REVIEW

**Comment by TreyLawrence** [comment]
RIP 😭

**Comment by ox** [comment]
lgtm

**Comment by imsobe** [comment]
🤔

**Comment by maiamcc** [comment]
Just in time for Halloween: zombie PRs!

**Comment by jeffreytierney** [comment]
is it web scale?

**Comment by ox** [comment]
More importantly, can we get this ready by Q1? Not sure if this can be cleared with our associates before the Q4 feature freeze.

**Pull request closed without merging**
